### ISSUE TITLE
enforcer.fail=false not working

### ISSUE THREAD

**Issue by nba1992** [ospector/mvn-enforce-concrete-version#1]
Hello.

i was trying to have some smooth changes in my company using non-ranges and i found this almost-perfect plugin.
Unfortunelly, during tests, i've just noticed that this plugin does not care about "enforcer.fail=false", and fails everytime, with or without enforcer.fail=false.
According to enforcer plugin documentation, if enforcer.fail=false, errors should "transform in" warnings and the build should not fail.

Can you please fix it?
Many Thanks and good work!

**Comment by ospector** [comment]
Hi,
I have not used maven or touched my original code for several years now....

If you would like to submit a pull request to fix this, I will gladly review and accept.

Anything beyond that is currently not possible.

**Comment by nba1992** [comment]
Hello.

@ospector everything is correct with your developed code.

The problem was that my pom.xml had <fail>true</fail>, and for some reason i didnt't get yet (using the latest version now enforcer ), -Denforcer.fail=true/false was not taking into priority via CLI.

After removing the property from plugin properties at pom.xml, everything was working properly.

I'm very sorrry for the confusion, and excelent work.

It's live now!

**Comment by ospector** [comment]
Thank you for letting me know. I appreciate it!
